// Generated by IB v0.7.2 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import "Stubs.h"

@implementation AppDelegate
@end

@implementation MainTableViewCell
@end

@implementation DecisionViewController
@end

@implementation MainViewController
@end

@implementation Con
@end

@implementation Decision
@end

@implementation Pro
@end

@implementation LongPressMenuView
@end

@implementation NSObject
@end

