// Generated by IB v0.7.2 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <CoreData/CoreData.h>

@interface AppDelegate: UIResponder <UIApplicationDelegate>
-(IBAction) window;
-(IBAction) storyboard;

@end

@interface MainTableViewCell: UITableViewCell
-(IBAction) layoutSubviews;
-(IBAction) decision;
-(IBAction) render_text_field;
-(IBAction) open_label;
-(IBAction) delete_label;
-(IBAction) create_cue_label;
-(IBAction) gradient_layer;
-(IBAction) colors;
-(IBAction) pan_gesture;
-(IBAction) handle_pan:(id) pan_gesture;
-(IBAction) state_began:(id) pan_gesture;
-(IBAction) state_changed:(id) pan_gesture;
-(IBAction) initial_swipe_cue:(id) label;
-(IBAction) final_swipe_cue:(id) label;
-(IBAction) complete_right_swipe_cue:(id) label;
-(IBAction) complete_left_swipe_cue:(id) label;
-(IBAction) state_ended:(id) pan_gesture;
-(IBAction) gestureRecognizerShouldBegin:(id) gesture_recognizer;
-(IBAction) textFieldShouldReturn:(id) text_field;
-(IBAction) textFieldShouldBeginEditing:(id) text_field;
-(IBAction) textFieldDidBeginEditing:(id) text_field;
-(IBAction) textFieldDidEndEditing:(id) text_field;

@end

@interface DecisionViewController: UIViewController

@property IBOutlet UILabel * decision_title;
@property IBOutlet UITableView * decision_table_view;

-(IBAction) viewDidLoad;
-(IBAction) decision_object:(id) decision;
-(IBAction) decisions_ordered;
-(IBAction) go_back;

@end

@interface MainViewController: UIViewController

@property IBOutlet UITableView * table_view;

-(IBAction) viewDidLoad;
-(IBAction) open_decision:(id) decision;
-(IBAction) decision_deleted:(id) decision;
-(IBAction) new_decision_added;

@end

@interface Con: CDQManagedObject
@end

@interface Decision: CDQManagedObject
@end

@interface Pro: CDQManagedObject
@end

