// Generated by IB v0.7.2 gem. Do not edit it manually
// Run `rake ib:open` to refresh

#import <UIKit/UIKit.h>
#import <Foundation/Foundation.h>
#import <CoreGraphics/CoreGraphics.h>
#import <CoreData/CoreData.h>

@interface AppDelegate: UIResponder <UIApplicationDelegate>
-(IBAction) window;
-(IBAction) storyboard;

@end

@interface MainTableViewCell: UITableViewCell
-(IBAction) layoutSubviews;
-(IBAction) decision;
-(IBAction) render_label;
-(IBAction) cross_label;
-(IBAction) create_cue_label;
-(IBAction) gradient_layer;
-(IBAction) colors;
-(IBAction) recognizer;
-(IBAction) handle_pan:(id) recognizer;
-(IBAction) state_began:(id) recognizer;
-(IBAction) state_changed:(id) recognizer;
-(IBAction) state_ended:(id) recognizer;
-(IBAction) gestureRecognizerShouldBegin:(id) gesture_recognizer;
-(IBAction) textFieldShouldReturn:(id) text_field;
-(IBAction) textFieldShouldBeginEditing:(id) text_field;
-(IBAction) textFieldDidBeginEditing:(id) text_field;
-(IBAction) textFieldDidEndEditing:(id) text_field;

@end

@interface MainViewController: UIViewController

@property IBOutlet UITableView * table_view;

-(IBAction) viewDidLoad;
-(IBAction) decision_deleted:(id) decision;
-(IBAction) new_decision_added;

@end

@interface Con: CDQManagedObject
@end

@interface Decision: CDQManagedObject
@end

@interface Pro: CDQManagedObject
@end

